### ISSUE TITLE
Rotational number-entering components unworkable

### ISSUE THREAD

**Issue by sleemans** [FirstLegoLeague/fllscoring#177] opened 2015-11-23 09:28 UTC
Saturday in Eindhoven and Sunday in Kortrijk I got a lot of complaints from the referees about the rotation components to enter numbers. On iPads, they kind-of work sometimes. However, on cheaper devices, they can be extremely annoying to use.

1) they are small and referees with big fingers have a lot of trouble to accurately click the increase and decrease buttons. Zooming in does not help because then 'swyping' does not work anymore. Moreover, after two clicks on these buttons, the browser interprets this as a double click and zooms out again.
2) they are too close to the scroll bar on the side of the screen. Hence, sometimes the page jumps up and down.
3) scrolling the page up/down is sometimes registered as a change in the scoring (->-unnoticed-<-). This leads to unnecessary unnoticed errors in the scoring.
4) Swyping left and right is unreliable: it feels almost random on what number the dial will end, even if the referee is positioning the dial accurately on a number and holding it still.

Some of these issues could be fixed by tweaking the layout, but I suggest to replace these components by something that works better. One idea would be to replace them with buttons, i.e. one button for each number. This will require some layout fiddling, but would solve all of the above issues. If anyone has other ideas, please let them come :)

**Comment by rikkertkoppes** [comment] 2015-11-23 09:32
Duplicate of #44

**Closed by rikkertkoppes** 2015-11-23 09:32 UTC
