### ISSUE TITLE
Review content of a score form

### ISSUE THREAD

**Issue by robvw** [FirstLegoLeague/fllscoring#129] opened 2014-12-13 16:01 UTC
If a referee doubts they filled in their form correctly, we currently have no way (except backend-hacking magic) to review exactly which missions were awarded or not. In order to facilitate "Oh wait, did I tick mission XYZ!?" verification, it would be useful to be able to open up the scoring sheet behind a score (even if we don't have actual edit capability, just reading it back).

**Comment by kmeesters** [comment] 2015-08-22 16:45
Related to #131

**Comment by kmeesters** [comment] 2015-08-22 17:15
Close duplicate of #64

**Closed by kmeesters** 2015-08-22 17:15 UTC
Labels: Optimization: UI / Usability, Requirements: feature request
